-- Gerado por Oracle SQL Developer Data Modeler 4.0.2.840
--   em:        2014-06-03 01:15:03 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE USER HR IDENTIFIED BY ACCOUNT UNLOCK ;

CREATE TABLE HR.TB_ALTERN
  (
    CD_ALTERN         NUMBER NOT NULL ,
    DS_ALTERN         VARCHAR2 (100 BYTE) ,
    TB_QUEST_CD_QUEST NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_ALTERN_PK ON HR.TB_ALTERN
  (
    TB_QUEST_CD_QUEST ASC , CD_ALTERN ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_ALTERN ADD CONSTRAINT TB_ALTERN_PK PRIMARY KEY ( TB_QUEST_CD_QUEST, CD_ALTERN ) USING INDEX HR.TB_ALTERN_PK ;

CREATE TABLE HR.TB_ALU
  (
    CD_ALU               NUMBER NOT NULL ,
    NM_ALU               VARCHAR2 (100 BYTE) ,
    TB_TUR_CD_TUR        NUMBER NOT NULL ,
    TB_LOGIN_CD_LOGIN    NUMBER NOT NULL ,
    CD_NIV               NUMBER ,
    TB_TUR_TB_CUR_CD_CUR NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_ALU__IDX ON HR.TB_ALU
  (
    TB_LOGIN_CD_LOGIN ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE UNIQUE INDEX HR.TB_ALU_PK ON HR.TB_ALU
  (
    CD_ALU ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_ALU ADD CONSTRAINT TB_ALU_PK PRIMARY KEY ( CD_ALU ) USING INDEX HR.TB_ALU_PK ;

CREATE TABLE HR.TB_AVALI
  (
    CD_AVALI        NUMBER NOT NULL ,
    TB_CONT_CD_CONT NUMBER NOT NULL ,
    TB_IMAG_CD_IMAG NUMBER NOT NULL ,
    NM_AVALI        VARCHAR2 (15 BYTE) ,
    TB_STAT_CD_STAT NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_AVALI__IDX ON HR.TB_AVALI
  (
    TB_STAT_CD_STAT ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE UNIQUE INDEX HR.TB_AVALI__IDXV1 ON HR.TB_AVALI
  (
    TB_IMAG_CD_IMAG ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE UNIQUE INDEX HR.TB_AVALI_PK ON HR.TB_AVALI
  (
    CD_AVALI ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_AVALI ADD CONSTRAINT TB_AVALI_PK PRIMARY KEY ( CD_AVALI ) USING INDEX HR.TB_AVALI_PK ;

CREATE TABLE HR.TB_AVALI_QUEST
  (
    TB_AVALI_CD_AVALI NUMBER NOT NULL ,
    TB_QUEST_CD_QUEST NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_AVALI_QUEST__IDX ON HR.TB_AVALI_QUEST
  (
    TB_AVALI_CD_AVALI ASC , TB_QUEST_CD_QUEST ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_AVALI_QUEST ADD CONSTRAINT TB_AVALI_QUEST__IDX PRIMARY KEY ( TB_AVALI_CD_AVALI, TB_QUEST_CD_QUEST ) USING INDEX HR.TB_AVALI_QUEST__IDX ;

CREATE TABLE HR.TB_CONT
  (
    CD_CONT         NUMBER NOT NULL ,
    TB_PROF_CD_PROF NUMBER NOT NULL ,
    TB_PROF_CD_CPF  NUMBER NOT NULL ,
    TB_IMAG_CD_IMAG NUMBER NOT NULL ,
    NM_CONT         VARCHAR2 (50 BYTE) ,
    DS_CONT CLOB ,
    TB_STAT_CD_STAT NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOB
  (
    DS_CONT
  )
  STORE AS
  (
    TABLESPACE USERS STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT ) CHUNK 8192 RETENTION ENABLE STORAGE IN ROW NOCACHE LOGGING
  ) ;
CREATE UNIQUE INDEX HR.TB_CONT__IDX ON HR.TB_CONT
  (
    TB_STAT_CD_STAT ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE UNIQUE INDEX HR.TB_CONT__IDXV1 ON HR.TB_CONT
  (
    TB_IMAG_CD_IMAG ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE UNIQUE INDEX HR.TB_CONT_PK ON HR.TB_CONT
  (
    CD_CONT ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_CONT ADD CONSTRAINT TB_CONT_PK PRIMARY KEY ( CD_CONT ) USING INDEX HR.TB_CONT_PK ;

CREATE TABLE HR.TB_CUR
  (
    CD_CUR NUMBER NOT NULL ,
    NM_CUR VARCHAR2 (45 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_CUR_PK ON HR.TB_CUR
  (
    CD_CUR ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_CUR ADD CONSTRAINT TB_CUR_PK PRIMARY KEY ( CD_CUR ) USING INDEX HR.TB_CUR_PK ;

CREATE TABLE HR.TB_CUR_DISCIP
  (
    TB_CUR_CD_CUR       NUMBER NOT NULL ,
    TB_DISCIP_CD_DISCIP NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_CUR_DISCIP__IDX ON HR.TB_CUR_DISCIP
  (
    TB_CUR_CD_CUR ASC , TB_DISCIP_CD_DISCIP ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_CUR_DISCIP ADD CONSTRAINT TB_CUR_DISCIP__IDX PRIMARY KEY ( TB_CUR_CD_CUR, TB_DISCIP_CD_DISCIP ) USING INDEX HR.TB_CUR_DISCIP__IDX ;

CREATE TABLE HR.TB_CUR_PERIO
  (
    TB_CUR_CD_CUR     NUMBER NOT NULL ,
    TB_PERIO_CD_PERIO NUMBER (3) NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_CUR_PERIO__IDX ON HR.TB_CUR_PERIO
  (
    TB_CUR_CD_CUR ASC , TB_PERIO_CD_PERIO ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_CUR_PERIO ADD CONSTRAINT TB_CUR_PERIO__IDX PRIMARY KEY ( TB_CUR_CD_CUR, TB_PERIO_CD_PERIO ) USING INDEX HR.TB_CUR_PERIO__IDX ;

CREATE TABLE HR.TB_DISCIP
  (
    CD_DISCIP NUMBER NOT NULL ,
    NM_DISCIP VARCHAR2 (45 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_DISCIP_PK ON HR.TB_DISCIP
  (
    CD_DISCIP ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_DISCIP ADD CONSTRAINT TB_DISCIP_PK PRIMARY KEY ( CD_DISCIP ) USING INDEX HR.TB_DISCIP_PK ;

CREATE TABLE HR.TB_DISCIP_PROF
  (
    TB_PROF_CD_PROF     NUMBER NOT NULL ,
    TB_PROF_CD_CPF      NUMBER NOT NULL ,
    TB_DISCIP_CD_DISCIP NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_DISCIP_PROF__IDX ON HR.TB_DISCIP_PROF
  (
    TB_PROF_CD_PROF ASC , TB_PROF_CD_CPF ASC , TB_DISCIP_CD_DISCIP ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_DISCIP_PROF ADD CONSTRAINT TB_DISCIP_PROF__IDX PRIMARY KEY ( TB_PROF_CD_PROF, TB_PROF_CD_CPF, TB_DISCIP_CD_DISCIP ) USING INDEX HR.TB_DISCIP_PROF__IDX ;

CREATE TABLE HR.TB_IMAG
  (
    CD_IMAG NUMBER NOT NULL ,
    NM_IMAG VARCHAR2 (100 BYTE) ,
    DS_URL  VARCHAR2 (100 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_IMAG_PK ON HR.TB_IMAG
  (
    CD_IMAG ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_IMAG ADD CONSTRAINT TB_IMAG_PK PRIMARY KEY ( CD_IMAG ) USING INDEX HR.TB_IMAG_PK ;

CREATE TABLE HR.TB_INST
  (
    CD_INST NUMBER NOT NULL ,
    NM_INST VARCHAR2 (50 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_INST_PK ON HR.TB_INST
  (
    CD_INST ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_INST ADD CONSTRAINT TB_INST_PK PRIMARY KEY ( CD_INST ) USING INDEX HR.TB_INST_PK ;

CREATE TABLE HR.TB_INST_CUR
  (
    TB_INST_CD_INST NUMBER NOT NULL ,
    TB_CUR_CD_CUR   NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_INST_CUR__IDX ON HR.TB_INST_CUR
  (
    TB_INST_CD_INST ASC , TB_CUR_CD_CUR ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_INST_CUR ADD CONSTRAINT TB_INST_CUR__IDX PRIMARY KEY ( TB_INST_CD_INST, TB_CUR_CD_CUR ) USING INDEX HR.TB_INST_CUR__IDX ;

CREATE TABLE HR.TB_LOGIN
  (
    CD_LOGIN NUMBER NOT NULL ,
    NM_EMAIL VARCHAR2 (50 BYTE) ,
    NM_SENHA VARCHAR2 (32 BYTE) ,
    TP_LOGIN NUMBER (1)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_LOGIN_PK ON HR.TB_LOGIN
  (
    CD_LOGIN ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_LOGIN ADD CONSTRAINT TB_LOGIN_PK PRIMARY KEY ( CD_LOGIN ) USING INDEX HR.TB_LOGIN_PK ;

CREATE TABLE HR.TB_PERIO
  (
    CD_PERIO NUMBER (3) NOT NULL ,
    NM_PERIO VARCHAR2 (15 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_PERIO_PK ON HR.TB_PERIO
  (
    CD_PERIO ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_PERIO ADD CONSTRAINT TB_PERIO_PK PRIMARY KEY ( CD_PERIO ) USING INDEX HR.TB_PERIO_PK ;

CREATE TABLE HR.TB_PROF
  (
    CD_PROF           NUMBER NOT NULL ,
    NM_PROF           VARCHAR2 (100 BYTE) ,
    CD_CPF            NUMBER NOT NULL ,
    TB_LOGIN_CD_LOGIN NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_PROF__IDX ON HR.TB_PROF
  (
    TB_LOGIN_CD_LOGIN ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
CREATE UNIQUE INDEX HR.TB_PROF_PK ON HR.TB_PROF
  (
    CD_PROF ASC , CD_CPF ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_PROF ADD CONSTRAINT TB_PROF_PK PRIMARY KEY ( CD_PROF, CD_CPF ) USING INDEX HR.TB_PROF_PK ;

CREATE TABLE HR.TB_QUEST
  (
    CD_QUEST NUMBER NOT NULL ,
    NM_QUEST VARCHAR2 (50 BYTE) ,
    DS_QUEST VARCHAR2 (1000 BYTE) ,
    IC_RESP  NUMBER ,
    CD_NIV   NUMBER
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_QUEST_PK ON HR.TB_QUEST
  (
    CD_QUEST ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_QUEST ADD CONSTRAINT TB_QUEST_PK PRIMARY KEY ( CD_QUEST ) USING INDEX HR.TB_QUEST_PK ;

CREATE TABLE HR.TB_STAT
  (
    CD_STAT NUMBER NOT NULL ,
    IC_STAT CHAR (1 BYTE) ,
    CD_ALU  NUMBER
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_STAT_PK ON HR.TB_STAT
  (
    CD_STAT ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_STAT ADD CONSTRAINT TB_STAT_PK PRIMARY KEY ( CD_STAT ) USING INDEX HR.TB_STAT_PK ;

CREATE TABLE HR.TB_TUR
  (
    CD_TUR        NUMBER NOT NULL ,
    NM_TUR        VARCHAR2 (10 BYTE) ,
    TB_CUR_CD_CUR NUMBER NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE USERS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX HR.TB_TUR_PK ON HR.TB_TUR
  (
    CD_TUR ASC , TB_CUR_CD_CUR ASC
  )
  TABLESPACE USERS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
  ALTER TABLE HR.TB_TUR ADD CONSTRAINT TB_TUR_PK PRIMARY KEY ( CD_TUR, TB_CUR_CD_CUR ) USING INDEX HR.TB_TUR_PK ;

ALTER TABLE HR.TB_CUR_PERIO ADD CONSTRAINT FK_ASS_10 FOREIGN KEY ( TB_PERIO_CD_PERIO ) REFERENCES HR.TB_PERIO ( CD_PERIO ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_DISCIP_PROF ADD CONSTRAINT FK_ASS_12 FOREIGN KEY ( TB_PROF_CD_PROF, TB_PROF_CD_CPF ) REFERENCES HR.TB_PROF ( CD_PROF, CD_CPF ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_DISCIP_PROF ADD CONSTRAINT FK_ASS_13 FOREIGN KEY ( TB_DISCIP_CD_DISCIP ) REFERENCES HR.TB_DISCIP ( CD_DISCIP ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_INST_CUR ADD CONSTRAINT FK_ASS_16 FOREIGN KEY ( TB_INST_CD_INST ) REFERENCES HR.TB_INST ( CD_INST ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_INST_CUR ADD CONSTRAINT FK_ASS_17 FOREIGN KEY ( TB_CUR_CD_CUR ) REFERENCES HR.TB_CUR ( CD_CUR ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_AVALI_QUEST ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( TB_AVALI_CD_AVALI ) REFERENCES HR.TB_AVALI ( CD_AVALI ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_AVALI_QUEST ADD CONSTRAINT FK_ASS_3 FOREIGN KEY ( TB_QUEST_CD_QUEST ) REFERENCES HR.TB_QUEST ( CD_QUEST ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_CUR_DISCIP ADD CONSTRAINT FK_ASS_7 FOREIGN KEY ( TB_CUR_CD_CUR ) REFERENCES HR.TB_CUR ( CD_CUR ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_CUR_DISCIP ADD CONSTRAINT FK_ASS_8 FOREIGN KEY ( TB_DISCIP_CD_DISCIP ) REFERENCES HR.TB_DISCIP ( CD_DISCIP ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_CUR_PERIO ADD CONSTRAINT FK_ASS_9 FOREIGN KEY ( TB_CUR_CD_CUR ) REFERENCES HR.TB_CUR ( CD_CUR ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_STAT ADD CONSTRAINT KF_ALU_STAT FOREIGN KEY ( CD_ALU ) REFERENCES HR.TB_ALU ( CD_ALU ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_ALTERN ADD CONSTRAINT TB_ALTERN_TB_QUEST_FK FOREIGN KEY ( TB_QUEST_CD_QUEST ) REFERENCES HR.TB_QUEST ( CD_QUEST ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_ALU ADD CONSTRAINT TB_ALU_TB_LOGIN_FK FOREIGN KEY ( TB_LOGIN_CD_LOGIN ) REFERENCES HR.TB_LOGIN ( CD_LOGIN ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_ALU ADD CONSTRAINT TB_ALU_TB_TUR_FK FOREIGN KEY ( TB_TUR_CD_TUR, TB_TUR_TB_CUR_CD_CUR ) REFERENCES HR.TB_TUR ( CD_TUR, TB_CUR_CD_CUR ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_AVALI ADD CONSTRAINT TB_AVALI_TB_CONT_FK FOREIGN KEY ( TB_CONT_CD_CONT ) REFERENCES HR.TB_CONT ( CD_CONT ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_AVALI ADD CONSTRAINT TB_AVALI_TB_IMAG_FK FOREIGN KEY ( TB_IMAG_CD_IMAG ) REFERENCES HR.TB_IMAG ( CD_IMAG ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_AVALI ADD CONSTRAINT TB_AVALI_TB_STAT_FK FOREIGN KEY ( TB_STAT_CD_STAT ) REFERENCES HR.TB_STAT ( CD_STAT ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_CONT ADD CONSTRAINT TB_CONT_TB_IMAG_FK FOREIGN KEY ( TB_IMAG_CD_IMAG ) REFERENCES HR.TB_IMAG ( CD_IMAG ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_CONT ADD CONSTRAINT TB_CONT_TB_PROF_FK FOREIGN KEY ( TB_PROF_CD_PROF, TB_PROF_CD_CPF ) REFERENCES HR.TB_PROF ( CD_PROF, CD_CPF ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_CONT ADD CONSTRAINT TB_CONT_TB_STAT_FK FOREIGN KEY ( TB_STAT_CD_STAT ) REFERENCES HR.TB_STAT ( CD_STAT ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_PROF ADD CONSTRAINT TB_PROF_TB_LOGIN_FK FOREIGN KEY ( TB_LOGIN_CD_LOGIN ) REFERENCES HR.TB_LOGIN ( CD_LOGIN ) NOT DEFERRABLE ;

ALTER TABLE HR.TB_TUR ADD CONSTRAINT TB_TUR_TB_CUR_FK FOREIGN KEY ( TB_CUR_CD_CUR ) REFERENCES HR.TB_CUR ( CD_CUR ) NOT DEFERRABLE ;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                            25
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
